# sets the "Present" property on the fan# object
# path:  create /system/chassis/motherboard/fan# object in inventory
# type:  whether tach or GPIOs //tomahawk has it in tach

- name: fan1
  path: /system/chassis/motherboard/fan1
  methods:
    - type: tach
      sensors:
        - fan1_0
        - fan1_1

- name: fan2
  path: /system/chassis/motherboard/fan2
  methods:
    - type: tach
      sensors:
        - fan2_0
        - fan2_1

- name: fan3
  path: /system/chassis/motherboard/fan3
  methods:
    - type: tach
      sensors:
        - fan3_0
        - fan3_1

- name: fan4
  path: /system/chassis/motherboard/fan4
  methods:
    - type: tach
      sensors:
        - fan4_0
        - fan4_1
